/*
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailodds.api;

import com.mailodds.ApiException;
import com.mailodds.model.ConfirmSubscription200Response;
import com.mailodds.model.CreateList201Response;
import com.mailodds.model.CreateListRequest;
import com.mailodds.model.DeletePolicyRule200Response;
import com.mailodds.model.ErrorResponse;
import com.mailodds.model.GetLists200Response;
import com.mailodds.model.GetSubscribers200Response;
import com.mailodds.model.SubscribeRequest;
import com.mailodds.model.UnsubscribeSubscriber200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriberListsApi
 */
@Disabled
public class SubscriberListsApiTest {

    private final SubscriberListsApi api = new SubscriberListsApi();

    /**
     * Confirm subscription
     *
     * Confirm a pending subscription via the token sent in the confirmation email. No authentication required. Redirects to the list&#39;s configured redirect URL if set, otherwise returns JSON. Tokens expire after 72 hours.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void confirmSubscriptionTest() throws ApiException {
        String token = null;
        ConfirmSubscription200Response response = api.confirmSubscription(token);
        // TODO: test validations
    }

    /**
     * Create a subscriber list
     *
     * Create a new subscriber list. Use lists to organize subscribers and manage double opt-in confirmation flows.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createListTest() throws ApiException {
        CreateListRequest createListRequest = null;
        CreateList201Response response = api.createList(createListRequest);
        // TODO: test validations
    }

    /**
     * Delete a subscriber list
     *
     * Soft-delete a subscriber list. Existing subscribers are retained but the list is no longer usable.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteListTest() throws ApiException {
        String listId = null;
        DeletePolicyRule200Response response = api.deleteList(listId);
        // TODO: test validations
    }

    /**
     * Get a subscriber list
     *
     * Get details of a specific subscriber list including subscriber and confirmed counts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        String listId = null;
        CreateList201Response response = api.getList(listId);
        // TODO: test validations
    }

    /**
     * List subscriber lists
     *
     * List all subscriber lists for the authenticated account with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListsTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        GetLists200Response response = api.getLists(page, perPage);
        // TODO: test validations
    }

    /**
     * List subscribers
     *
     * List paginated subscribers for a specific list. Optionally filter by status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubscribersTest() throws ApiException {
        String listId = null;
        Integer page = null;
        Integer perPage = null;
        String status = null;
        GetSubscribers200Response response = api.getSubscribers(listId, page, perPage, status);
        // TODO: test validations
    }

    /**
     * Subscribe to a list
     *
     * Add a subscriber to a list and initiate the double opt-in confirmation flow. The subscriber receives a confirmation email and must click the link to confirm. Rate limited to 10 requests/min per IP and 1000/hour per account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void subscribeTest() throws ApiException {
        String listId = null;
        SubscribeRequest subscribeRequest = null;
        UnsubscribeSubscriber200Response response = api.subscribe(listId, subscribeRequest);
        // TODO: test validations
    }

    /**
     * Unsubscribe a subscriber
     *
     * Set a subscriber&#39;s status to unsubscribed. The consent record is retained for compliance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unsubscribeSubscriberTest() throws ApiException {
        String listId = null;
        String subscriberId = null;
        UnsubscribeSubscriber200Response response = api.unsubscribeSubscriber(listId, subscriberId);
        // TODO: test validations
    }

}
