/*
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailodds.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailodds.model.DeliverRequestOptions;
import com.mailodds.model.DeliverRequestStructuredData;
import com.mailodds.model.DeliverRequestToInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailodds.JSON;

/**
 * DeliverRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T01:37:38.039547555+01:00[Europe/Amsterdam]", comments = "Generator version: 7.19.0")
public class DeliverRequest {
  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  @javax.annotation.Nonnull
  private List<DeliverRequestToInner> to = new ArrayList<>();

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  @javax.annotation.Nonnull
  private String from;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nonnull
  private String subject;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nullable
  private String html;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_DOMAIN_ID = "domain_id";
  @SerializedName(SERIALIZED_NAME_DOMAIN_ID)
  @javax.annotation.Nonnull
  private String domainId;

  public static final String SERIALIZED_NAME_REPLY_TO = "reply_to";
  @SerializedName(SERIALIZED_NAME_REPLY_TO)
  @javax.annotation.Nullable
  private String replyTo;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nullable
  private Object headers;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  /**
   * Campaign type for JSON-LD auto-generation
   */
  @JsonAdapter(CampaignTypeEnum.Adapter.class)
  public enum CampaignTypeEnum {
    ORDER_CONFIRMATION("order_confirmation"),
    
    SHIPPING_NOTIFICATION("shipping_notification"),
    
    SUBSCRIPTION_CONFIRM("subscription_confirm"),
    
    REVIEW_REQUEST("review_request"),
    
    EVENT_INVITATION("event_invitation"),
    
    PROMOTIONAL("promotional"),
    
    WELCOME("welcome"),
    
    PASSWORD_RESET("password_reset"),
    
    APPOINTMENT_REMINDER("appointment_reminder"),
    
    TICKET_CONFIRMATION("ticket_confirmation");

    private String value;

    CampaignTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CampaignTypeEnum fromValue(String value) {
      for (CampaignTypeEnum b : CampaignTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CampaignTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CampaignTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CampaignTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CampaignTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CampaignTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CAMPAIGN_TYPE = "campaign_type";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_TYPE)
  @javax.annotation.Nullable
  private CampaignTypeEnum campaignType;

  public static final String SERIALIZED_NAME_STRUCTURED_DATA = "structured_data";
  @SerializedName(SERIALIZED_NAME_STRUCTURED_DATA)
  @javax.annotation.Nullable
  private DeliverRequestStructuredData structuredData;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  @javax.annotation.Nullable
  private DeliverRequestOptions options;

  public DeliverRequest() {
  }

  public DeliverRequest to(@javax.annotation.Nonnull List<DeliverRequestToInner> to) {
    this.to = to;
    return this;
  }

  public DeliverRequest addToItem(DeliverRequestToInner toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

  /**
   * List of recipient email addresses
   * @return to
   */
  @javax.annotation.Nonnull
  public List<DeliverRequestToInner> getTo() {
    return to;
  }

  public void setTo(@javax.annotation.Nonnull List<DeliverRequestToInner> to) {
    this.to = to;
  }


  public DeliverRequest from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Sender email address (must match sending domain)
   * @return from
   */
  @javax.annotation.Nonnull
  public String getFrom() {
    return from;
  }

  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public DeliverRequest subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Email subject line
   * @return subject
   */
  @javax.annotation.Nonnull
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public DeliverRequest html(@javax.annotation.Nullable String html) {
    this.html = html;
    return this;
  }

  /**
   * HTML email body
   * @return html
   */
  @javax.annotation.Nullable
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nullable String html) {
    this.html = html;
  }


  public DeliverRequest text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Plain text email body
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public DeliverRequest domainId(@javax.annotation.Nonnull String domainId) {
    this.domainId = domainId;
    return this;
  }

  /**
   * Sending domain UUID
   * @return domainId
   */
  @javax.annotation.Nonnull
  public String getDomainId() {
    return domainId;
  }

  public void setDomainId(@javax.annotation.Nonnull String domainId) {
    this.domainId = domainId;
  }


  public DeliverRequest replyTo(@javax.annotation.Nullable String replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Reply-to address
   * @return replyTo
   */
  @javax.annotation.Nullable
  public String getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(@javax.annotation.Nullable String replyTo) {
    this.replyTo = replyTo;
  }


  public DeliverRequest headers(@javax.annotation.Nullable Object headers) {
    this.headers = headers;
    return this;
  }

  /**
   * Extra email headers
   * @return headers
   */
  @javax.annotation.Nullable
  public Object getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nullable Object headers) {
    this.headers = headers;
  }


  public DeliverRequest tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public DeliverRequest addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Tags for categorization
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public DeliverRequest campaignType(@javax.annotation.Nullable CampaignTypeEnum campaignType) {
    this.campaignType = campaignType;
    return this;
  }

  /**
   * Campaign type for JSON-LD auto-generation
   * @return campaignType
   */
  @javax.annotation.Nullable
  public CampaignTypeEnum getCampaignType() {
    return campaignType;
  }

  public void setCampaignType(@javax.annotation.Nullable CampaignTypeEnum campaignType) {
    this.campaignType = campaignType;
  }


  public DeliverRequest structuredData(@javax.annotation.Nullable DeliverRequestStructuredData structuredData) {
    this.structuredData = structuredData;
    return this;
  }

  /**
   * Get structuredData
   * @return structuredData
   */
  @javax.annotation.Nullable
  public DeliverRequestStructuredData getStructuredData() {
    return structuredData;
  }

  public void setStructuredData(@javax.annotation.Nullable DeliverRequestStructuredData structuredData) {
    this.structuredData = structuredData;
  }


  public DeliverRequest options(@javax.annotation.Nullable DeliverRequestOptions options) {
    this.options = options;
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nullable
  public DeliverRequestOptions getOptions() {
    return options;
  }

  public void setOptions(@javax.annotation.Nullable DeliverRequestOptions options) {
    this.options = options;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliverRequest deliverRequest = (DeliverRequest) o;
    return Objects.equals(this.to, deliverRequest.to) &&
        Objects.equals(this.from, deliverRequest.from) &&
        Objects.equals(this.subject, deliverRequest.subject) &&
        Objects.equals(this.html, deliverRequest.html) &&
        Objects.equals(this.text, deliverRequest.text) &&
        Objects.equals(this.domainId, deliverRequest.domainId) &&
        Objects.equals(this.replyTo, deliverRequest.replyTo) &&
        Objects.equals(this.headers, deliverRequest.headers) &&
        Objects.equals(this.tags, deliverRequest.tags) &&
        Objects.equals(this.campaignType, deliverRequest.campaignType) &&
        Objects.equals(this.structuredData, deliverRequest.structuredData) &&
        Objects.equals(this.options, deliverRequest.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, from, subject, html, text, domainId, replyTo, headers, tags, campaignType, structuredData, options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliverRequest {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    domainId: ").append(toIndentedString(domainId)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    campaignType: ").append(toIndentedString(campaignType)).append("\n");
    sb.append("    structuredData: ").append(toIndentedString(structuredData)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("to", "from", "subject", "html", "text", "domain_id", "reply_to", "headers", "tags", "campaign_type", "structured_data", "options"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("to", "from", "subject", "domain_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeliverRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeliverRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DeliverRequest is not found in the empty JSON string", DeliverRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeliverRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("to").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `to` to be an array in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }

      JsonArray jsonArrayto = jsonObj.getAsJsonArray("to");
      // validate the required field `to` (array)
      for (int i = 0; i < jsonArrayto.size(); i++) {
        DeliverRequestToInner.validateJsonElement(jsonArrayto.get(i));
      };
      if (!jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if (!jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("html") != null && !jsonObj.get("html").isJsonNull()) && !jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if (!jsonObj.get("domain_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `domain_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain_id").toString()));
      }
      if ((jsonObj.get("reply_to") != null && !jsonObj.get("reply_to").isJsonNull()) && !jsonObj.get("reply_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reply_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reply_to").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if ((jsonObj.get("campaign_type") != null && !jsonObj.get("campaign_type").isJsonNull()) && !jsonObj.get("campaign_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `campaign_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaign_type").toString()));
      }
      // validate the optional field `campaign_type`
      if (jsonObj.get("campaign_type") != null && !jsonObj.get("campaign_type").isJsonNull()) {
        CampaignTypeEnum.validateJsonElement(jsonObj.get("campaign_type"));
      }
      // validate the optional field `structured_data`
      if (jsonObj.get("structured_data") != null && !jsonObj.get("structured_data").isJsonNull()) {
        DeliverRequestStructuredData.validateJsonElement(jsonObj.get("structured_data"));
      }
      // validate the optional field `options`
      if (jsonObj.get("options") != null && !jsonObj.get("options").isJsonNull()) {
        DeliverRequestOptions.validateJsonElement(jsonObj.get("options"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeliverRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeliverRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeliverRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeliverRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeliverRequest>() {
           @Override
           public void write(JsonWriter out, DeliverRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeliverRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeliverRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeliverRequest
   * @throws IOException if the JSON string is invalid with respect to DeliverRequest
   */
  public static DeliverRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeliverRequest.class);
  }

  /**
   * Convert an instance of DeliverRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

