/*
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailodds.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailodds.JSON;

/**
 * ValidateBatch200ResponseSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-08T17:48:30.569515929+01:00[Europe/Amsterdam]", comments = "Generator version: 7.19.0")
public class ValidateBatch200ResponseSummary {
  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nullable
  private Integer valid;

  public static final String SERIALIZED_NAME_INVALID = "invalid";
  @SerializedName(SERIALIZED_NAME_INVALID)
  @javax.annotation.Nullable
  private Integer invalid;

  public static final String SERIALIZED_NAME_CATCH_ALL = "catch_all";
  @SerializedName(SERIALIZED_NAME_CATCH_ALL)
  @javax.annotation.Nullable
  private Integer catchAll;

  public static final String SERIALIZED_NAME_UNKNOWN = "unknown";
  @SerializedName(SERIALIZED_NAME_UNKNOWN)
  @javax.annotation.Nullable
  private Integer unknown;

  public static final String SERIALIZED_NAME_DO_NOT_MAIL = "do_not_mail";
  @SerializedName(SERIALIZED_NAME_DO_NOT_MAIL)
  @javax.annotation.Nullable
  private Integer doNotMail;

  public ValidateBatch200ResponseSummary() {
  }

  public ValidateBatch200ResponseSummary valid(@javax.annotation.Nullable Integer valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nullable
  public Integer getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nullable Integer valid) {
    this.valid = valid;
  }


  public ValidateBatch200ResponseSummary invalid(@javax.annotation.Nullable Integer invalid) {
    this.invalid = invalid;
    return this;
  }

  /**
   * Get invalid
   * @return invalid
   */
  @javax.annotation.Nullable
  public Integer getInvalid() {
    return invalid;
  }

  public void setInvalid(@javax.annotation.Nullable Integer invalid) {
    this.invalid = invalid;
  }


  public ValidateBatch200ResponseSummary catchAll(@javax.annotation.Nullable Integer catchAll) {
    this.catchAll = catchAll;
    return this;
  }

  /**
   * Get catchAll
   * @return catchAll
   */
  @javax.annotation.Nullable
  public Integer getCatchAll() {
    return catchAll;
  }

  public void setCatchAll(@javax.annotation.Nullable Integer catchAll) {
    this.catchAll = catchAll;
  }


  public ValidateBatch200ResponseSummary unknown(@javax.annotation.Nullable Integer unknown) {
    this.unknown = unknown;
    return this;
  }

  /**
   * Get unknown
   * @return unknown
   */
  @javax.annotation.Nullable
  public Integer getUnknown() {
    return unknown;
  }

  public void setUnknown(@javax.annotation.Nullable Integer unknown) {
    this.unknown = unknown;
  }


  public ValidateBatch200ResponseSummary doNotMail(@javax.annotation.Nullable Integer doNotMail) {
    this.doNotMail = doNotMail;
    return this;
  }

  /**
   * Get doNotMail
   * @return doNotMail
   */
  @javax.annotation.Nullable
  public Integer getDoNotMail() {
    return doNotMail;
  }

  public void setDoNotMail(@javax.annotation.Nullable Integer doNotMail) {
    this.doNotMail = doNotMail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateBatch200ResponseSummary validateBatch200ResponseSummary = (ValidateBatch200ResponseSummary) o;
    return Objects.equals(this.valid, validateBatch200ResponseSummary.valid) &&
        Objects.equals(this.invalid, validateBatch200ResponseSummary.invalid) &&
        Objects.equals(this.catchAll, validateBatch200ResponseSummary.catchAll) &&
        Objects.equals(this.unknown, validateBatch200ResponseSummary.unknown) &&
        Objects.equals(this.doNotMail, validateBatch200ResponseSummary.doNotMail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, invalid, catchAll, unknown, doNotMail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateBatch200ResponseSummary {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    invalid: ").append(toIndentedString(invalid)).append("\n");
    sb.append("    catchAll: ").append(toIndentedString(catchAll)).append("\n");
    sb.append("    unknown: ").append(toIndentedString(unknown)).append("\n");
    sb.append("    doNotMail: ").append(toIndentedString(doNotMail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("valid", "invalid", "catch_all", "unknown", "do_not_mail"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ValidateBatch200ResponseSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ValidateBatch200ResponseSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ValidateBatch200ResponseSummary is not found in the empty JSON string", ValidateBatch200ResponseSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ValidateBatch200ResponseSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ValidateBatch200ResponseSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ValidateBatch200ResponseSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ValidateBatch200ResponseSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ValidateBatch200ResponseSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ValidateBatch200ResponseSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<ValidateBatch200ResponseSummary>() {
           @Override
           public void write(JsonWriter out, ValidateBatch200ResponseSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ValidateBatch200ResponseSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ValidateBatch200ResponseSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ValidateBatch200ResponseSummary
   * @throws IOException if the JSON string is invalid with respect to ValidateBatch200ResponseSummary
   */
  public static ValidateBatch200ResponseSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ValidateBatch200ResponseSummary.class);
  }

  /**
   * Convert an instance of ValidateBatch200ResponseSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

