/*
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailodds.api;

import com.mailodds.ApiCallback;
import com.mailodds.ApiClient;
import com.mailodds.ApiException;
import com.mailodds.ApiResponse;
import com.mailodds.Configuration;
import com.mailodds.Pair;
import com.mailodds.ProgressRequestBody;
import com.mailodds.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mailodds.model.AddSuppressionRequest;
import com.mailodds.model.AddSuppressionResponse;
import com.mailodds.model.CheckSuppressionRequest;
import com.mailodds.model.ErrorResponse;
import com.mailodds.model.RemoveSuppression200Response;
import com.mailodds.model.RemoveSuppressionRequest;
import com.mailodds.model.SuppressionCheckResponse;
import com.mailodds.model.SuppressionListResponse;
import com.mailodds.model.SuppressionStatsResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SuppressionListsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SuppressionListsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SuppressionListsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addSuppression
     * @param addSuppressionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addSuppressionCall(@javax.annotation.Nonnull AddSuppressionRequest addSuppressionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addSuppressionRequest;

        // create path and map variables
        String localVarPath = "/v1/suppression";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addSuppressionValidateBeforeCall(@javax.annotation.Nonnull AddSuppressionRequest addSuppressionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'addSuppressionRequest' is set
        if (addSuppressionRequest == null) {
            throw new ApiException("Missing the required parameter 'addSuppressionRequest' when calling addSuppression(Async)");
        }

        return addSuppressionCall(addSuppressionRequest, _callback);

    }

    /**
     * Add suppression entries
     * Add emails or domains to the suppression list.
     * @param addSuppressionRequest  (required)
     * @return AddSuppressionResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public AddSuppressionResponse addSuppression(@javax.annotation.Nonnull AddSuppressionRequest addSuppressionRequest) throws ApiException {
        ApiResponse<AddSuppressionResponse> localVarResp = addSuppressionWithHttpInfo(addSuppressionRequest);
        return localVarResp.getData();
    }

    /**
     * Add suppression entries
     * Add emails or domains to the suppression list.
     * @param addSuppressionRequest  (required)
     * @return ApiResponse&lt;AddSuppressionResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AddSuppressionResponse> addSuppressionWithHttpInfo(@javax.annotation.Nonnull AddSuppressionRequest addSuppressionRequest) throws ApiException {
        okhttp3.Call localVarCall = addSuppressionValidateBeforeCall(addSuppressionRequest, null);
        Type localVarReturnType = new TypeToken<AddSuppressionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add suppression entries (asynchronously)
     * Add emails or domains to the suppression list.
     * @param addSuppressionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addSuppressionAsync(@javax.annotation.Nonnull AddSuppressionRequest addSuppressionRequest, final ApiCallback<AddSuppressionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addSuppressionValidateBeforeCall(addSuppressionRequest, _callback);
        Type localVarReturnType = new TypeToken<AddSuppressionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for checkSuppression
     * @param checkSuppressionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression check result </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkSuppressionCall(@javax.annotation.Nonnull CheckSuppressionRequest checkSuppressionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = checkSuppressionRequest;

        // create path and map variables
        String localVarPath = "/v1/suppression/check";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkSuppressionValidateBeforeCall(@javax.annotation.Nonnull CheckSuppressionRequest checkSuppressionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'checkSuppressionRequest' is set
        if (checkSuppressionRequest == null) {
            throw new ApiException("Missing the required parameter 'checkSuppressionRequest' when calling checkSuppression(Async)");
        }

        return checkSuppressionCall(checkSuppressionRequest, _callback);

    }

    /**
     * Check suppression status
     * Check if an email is suppressed.
     * @param checkSuppressionRequest  (required)
     * @return SuppressionCheckResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression check result </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public SuppressionCheckResponse checkSuppression(@javax.annotation.Nonnull CheckSuppressionRequest checkSuppressionRequest) throws ApiException {
        ApiResponse<SuppressionCheckResponse> localVarResp = checkSuppressionWithHttpInfo(checkSuppressionRequest);
        return localVarResp.getData();
    }

    /**
     * Check suppression status
     * Check if an email is suppressed.
     * @param checkSuppressionRequest  (required)
     * @return ApiResponse&lt;SuppressionCheckResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression check result </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SuppressionCheckResponse> checkSuppressionWithHttpInfo(@javax.annotation.Nonnull CheckSuppressionRequest checkSuppressionRequest) throws ApiException {
        okhttp3.Call localVarCall = checkSuppressionValidateBeforeCall(checkSuppressionRequest, null);
        Type localVarReturnType = new TypeToken<SuppressionCheckResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Check suppression status (asynchronously)
     * Check if an email is suppressed.
     * @param checkSuppressionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression check result </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkSuppressionAsync(@javax.annotation.Nonnull CheckSuppressionRequest checkSuppressionRequest, final ApiCallback<SuppressionCheckResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkSuppressionValidateBeforeCall(checkSuppressionRequest, _callback);
        Type localVarReturnType = new TypeToken<SuppressionCheckResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSuppressionStats
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression statistics </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSuppressionStatsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/suppression/stats";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSuppressionStatsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getSuppressionStatsCall(_callback);

    }

    /**
     * Get suppression statistics
     * Get statistics about the suppression list.
     * @return SuppressionStatsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression statistics </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public SuppressionStatsResponse getSuppressionStats() throws ApiException {
        ApiResponse<SuppressionStatsResponse> localVarResp = getSuppressionStatsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get suppression statistics
     * Get statistics about the suppression list.
     * @return ApiResponse&lt;SuppressionStatsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression statistics </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SuppressionStatsResponse> getSuppressionStatsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getSuppressionStatsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<SuppressionStatsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get suppression statistics (asynchronously)
     * Get statistics about the suppression list.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression statistics </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSuppressionStatsAsync(final ApiCallback<SuppressionStatsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSuppressionStatsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<SuppressionStatsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listSuppression
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression list </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listSuppressionCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String type, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/suppression";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listSuppressionValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String type, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        return listSuppressionCall(page, perPage, type, search, _callback);

    }

    /**
     * List suppression entries
     * List all suppression entries for the account.
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @return SuppressionListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression list </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public SuppressionListResponse listSuppression(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String type, @javax.annotation.Nullable String search) throws ApiException {
        ApiResponse<SuppressionListResponse> localVarResp = listSuppressionWithHttpInfo(page, perPage, type, search);
        return localVarResp.getData();
    }

    /**
     * List suppression entries
     * List all suppression entries for the account.
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @return ApiResponse&lt;SuppressionListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression list </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SuppressionListResponse> listSuppressionWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String type, @javax.annotation.Nullable String search) throws ApiException {
        okhttp3.Call localVarCall = listSuppressionValidateBeforeCall(page, perPage, type, search, null);
        Type localVarReturnType = new TypeToken<SuppressionListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List suppression entries (asynchronously)
     * List all suppression entries for the account.
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Suppression list </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listSuppressionAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String type, @javax.annotation.Nullable String search, final ApiCallback<SuppressionListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listSuppressionValidateBeforeCall(page, perPage, type, search, _callback);
        Type localVarReturnType = new TypeToken<SuppressionListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for removeSuppression
     * @param removeSuppressionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeSuppressionCall(@javax.annotation.Nonnull RemoveSuppressionRequest removeSuppressionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = removeSuppressionRequest;

        // create path and map variables
        String localVarPath = "/v1/suppression";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call removeSuppressionValidateBeforeCall(@javax.annotation.Nonnull RemoveSuppressionRequest removeSuppressionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'removeSuppressionRequest' is set
        if (removeSuppressionRequest == null) {
            throw new ApiException("Missing the required parameter 'removeSuppressionRequest' when calling removeSuppression(Async)");
        }

        return removeSuppressionCall(removeSuppressionRequest, _callback);

    }

    /**
     * Remove suppression entries
     * Remove emails or domains from the suppression list.
     * @param removeSuppressionRequest  (required)
     * @return RemoveSuppression200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public RemoveSuppression200Response removeSuppression(@javax.annotation.Nonnull RemoveSuppressionRequest removeSuppressionRequest) throws ApiException {
        ApiResponse<RemoveSuppression200Response> localVarResp = removeSuppressionWithHttpInfo(removeSuppressionRequest);
        return localVarResp.getData();
    }

    /**
     * Remove suppression entries
     * Remove emails or domains from the suppression list.
     * @param removeSuppressionRequest  (required)
     * @return ApiResponse&lt;RemoveSuppression200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RemoveSuppression200Response> removeSuppressionWithHttpInfo(@javax.annotation.Nonnull RemoveSuppressionRequest removeSuppressionRequest) throws ApiException {
        okhttp3.Call localVarCall = removeSuppressionValidateBeforeCall(removeSuppressionRequest, null);
        Type localVarReturnType = new TypeToken<RemoveSuppression200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Remove suppression entries (asynchronously)
     * Remove emails or domains from the suppression list.
     * @param removeSuppressionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Entries removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized - Invalid or missing API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeSuppressionAsync(@javax.annotation.Nonnull RemoveSuppressionRequest removeSuppressionRequest, final ApiCallback<RemoveSuppression200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeSuppressionValidateBeforeCall(removeSuppressionRequest, _callback);
        Type localVarReturnType = new TypeToken<RemoveSuppression200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
